FROM node:14-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
# COPY package*.json /app

# RUN npm install --no-optional && npm cache clean --force

# If you are building your code for production
# RUN npm ci --only=production
# RUN npm install nx -g
# Bundle app source
# COPY ./ /app
COPY dist/apps/api /app/

EXPOSE 3333
# CMD [ "npx","nx", "serve","api"]

RUN npm i
CMD ["node","main.js"]
