version: '3'

services:
  api:
    container_name: practice_api
    build:
      context: ./
      dockerfile: Dockerfile-api
    image: api
    ports:
      - 3333:3333

  # frontend:
  #   container_name: practice_frontend
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile-frontend
  #   image: frontend
  #   ports:
  #     - 4200:4200

  frontend-nginx:
    container_name: practice_nginx
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    image: frontend-nginx
    ports:
      - 4300:80
